# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
title: AI & Biases
email: dechantoine@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my github pages ! Here I will wrote about two of my passions: AI and biases.

url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AI_Biases
github_username:  dechantoine

author:
  name: "Antoine Déchappe"
  bio: "Data Scientist & ML Engineer. Currently tuning models for Leroy Merlin FR"
  twitter: "https://twitter.com/dechantoine"
  github: "https://github.com/dechantoine"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
 - jekyll-feed
 - jekyll-remote-theme 
  